### ISSUE TITLE
Fixed Random Seed

### ISSUE THREAD

**Issue by colemathis** [AgentElement/alchemy-reimplemented#5]
We need to be able to control the random number generator, so we should be able to set the seed somewhere in the config file.

**Comment by colemathis** [comment]
There's two different random seeds we care about, the generator seed and the reactor seed. These will be set independently.

**Comment by AgentElement** [comment]
Implemented in [this commit](https://github.com/AgentElement/alchemy-reimplemented/commit/4458d51a0345fc84d41f7c69cb69ce8d2ab663e5). The generator and reactor seed were already split.
